services:
  migrate:
    build: .
    command: [ "python", "manage.py", "migrate" ]
    env_file:
      - .env
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: studio.settings
      ROOT_PATH: /
      DEBUG: False
      POSTGRES_DB: studio
      POSTGRES_HOST: db
      POSTGRES_USER: studio
      POSTGRES_PASSWORD: password
  web:
    build: .
    volumes:
      - .:/code
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: studio.settings
      ROOT_PATH: /
      DEBUG: False
      POSTGRES_DB: studio
      POSTGRES_USER: studio
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: password
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: studio
      POSTGRES_USER: studio
      POSTGRES_PASSWORD: studio
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: