# Generated by Django 5.1.1 on 2024-09-20 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
