# Generated by Django 5.1.1 on 2024-09-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_report_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="repo",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
