# Generated by Django 5.1.2 on 2024-10-17 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr_manager', '0003_alter_pullrequestreview_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewfinding',
            name='recommendation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviewfinding',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='pr_manager.pullrequestreview'),
        ),
    ]
