# Generated by Django 5.1.2 on 2024-11-18 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr_manager', '0005_pullrequestreview_pr_number'),
        ('repositories', '0003_bookmarkedrepo_img_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PullRequestChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pr_number', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt', models.TextField(null=True)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositories.bookmarkedrepo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
