# Generated by Django 5.1.2 on 2024-11-18 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr_manager', '0006_pullrequestchangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequestchangerequest',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
