# Generated by Django 5.1.3 on 2024-11-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr_manager', '0007_pullrequestchangerequest_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewfinding',
            name='dismissed',
            field=models.BooleanField(default=False),
        ),
    ]
