# Generated by Django 5.1.1 on 2024-09-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0002_bookmarkedrepo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarkedrepo',
            name='img_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
